// <auto-generated />
using System;
using MediaManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MediaManagerDbContext))]
    partial class MediaManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaManager.Shared.Domain.AccessRequest", b =>
                {
                    b.Property<int>("UserRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserRequestId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDenied")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserRequestId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("AccessRequests", (string)null);
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.LibraryBucket", b =>
                {
                    b.Property<int>("LibraryBucketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LibraryBucketId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GroupType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(750)
                        .HasColumnType("character varying(750)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("LibraryBucketId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("LibraryBuckets", (string)null);
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.LibraryItem", b =>
                {
                    b.Property<int>("LibraryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LibraryItemId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int?>("LibraryBucketId")
                        .HasColumnType("integer");

                    b.Property<int?>("MediaId")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .HasMaxLength(750)
                        .HasColumnType("character varying(750)");

                    b.Property<string>("Name")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("OwnedFormat")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("LibraryItemId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LibraryBucketId");

                    b.HasIndex("MediaId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("LibraryItems", (string)null);
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.LibraryRequest", b =>
                {
                    b.Property<int>("LibraryRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LibraryRequestId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RelevantLink")
                        .HasMaxLength(750)
                        .HasColumnType("character varying(750)");

                    b.Property<string>("RequestTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("LibraryRequestId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("LibraryRequests", (string)null);
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.LibrarySubItem", b =>
                {
                    b.Property<int>("LibrarySubItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LibrarySubItemId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LibraryItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("MediaId")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("character varying(750)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("OwnedFormat")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LibrarySubItemId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LibraryItemId");

                    b.HasIndex("MediaId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("LibrarySubItems", (string)null);
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.Media", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MediaId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("ExternalStorageKey")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAlwaysAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnMediaServer")
                        .HasColumnType("boolean");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("StorageGuid")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MediaId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Media", (string)null);
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.MediaHistory", b =>
                {
                    b.Property<int>("MediaHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MediaHistoryId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("ActionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ActionUser")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<string>("StorageGuid")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("MediaHistoryId");

                    b.HasIndex("ActionUser");

                    b.HasIndex("MediaId");

                    b.ToTable("MediaHistory", (string)null);
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PermissionId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoleId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolePermissionId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.UserPermission", b =>
                {
                    b.Property<int>("UserPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserPermissionId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserPermissionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions", (string)null);
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.AccessRequest", b =>
                {
                    b.HasOne("MediaManager.Shared.Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("AccessRequests_CreatedBy_Users_UserId");

                    b.HasOne("MediaManager.Shared.Domain.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("AccessRequests_UpdatedBy_Users_UserId");

                    b.Navigation("Creator");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.LibraryBucket", b =>
                {
                    b.HasOne("MediaManager.Shared.Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("LibraryBucket_CreatedBy_Users_UserId");

                    b.HasOne("MediaManager.Shared.Domain.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("LibraryBucket_UpdatedBy_Users_UserId");

                    b.Navigation("Creator");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.LibraryItem", b =>
                {
                    b.HasOne("MediaManager.Shared.Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("LibraryItems_CreatedBy_Users_UserId");

                    b.HasOne("MediaManager.Shared.Domain.LibraryBucket", "LibraryBucket")
                        .WithMany("LibraryItems")
                        .HasForeignKey("LibraryBucketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("LibraryItems_LibraryBucketId_LibraryBuckets_LibraryBucketId");

                    b.HasOne("MediaManager.Shared.Domain.Media", "Media")
                        .WithMany("LibraryItems")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("LibraryItems_MediaId_Media_MediaId");

                    b.HasOne("MediaManager.Shared.Domain.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("LibraryItems_UpdatedBy_Users_UserId");

                    b.Navigation("Creator");

                    b.Navigation("LibraryBucket");

                    b.Navigation("Media");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.LibraryRequest", b =>
                {
                    b.HasOne("MediaManager.Shared.Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("LibraryRequests_CreatedBy_Users_UserId");

                    b.HasOne("MediaManager.Shared.Domain.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("LibraryRequests_UpdatedBy_Users_UserId");

                    b.Navigation("Creator");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.LibrarySubItem", b =>
                {
                    b.HasOne("MediaManager.Shared.Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("LibrarySubItems_CreatedBy_Users_UserId");

                    b.HasOne("MediaManager.Shared.Domain.LibraryItem", "LibraryItem")
                        .WithMany("LibrarySubItems")
                        .HasForeignKey("LibraryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("LibrarySubItems_LibraryItemId_LibraryItems_LibraryItemId");

                    b.HasOne("MediaManager.Shared.Domain.Media", "Media")
                        .WithMany("LibrarySubItems")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("LibrarySubItems_MediaId_Media_MediaId");

                    b.HasOne("MediaManager.Shared.Domain.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("LibrarySubItems_UpdatedBy_Users_UserId");

                    b.Navigation("Creator");

                    b.Navigation("LibraryItem");

                    b.Navigation("Media");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.Media", b =>
                {
                    b.HasOne("MediaManager.Shared.Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Media_CreatedBy_Users_UserId");

                    b.HasOne("MediaManager.Shared.Domain.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("Media_UpdatedBy_Users_UserId");

                    b.Navigation("Creator");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.MediaHistory", b =>
                {
                    b.HasOne("MediaManager.Shared.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("ActionUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("MediaHistory_ActionUser_Users_UserId");

                    b.HasOne("MediaManager.Shared.Domain.Media", "Media")
                        .WithMany("History")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("MediaHistory_MediaId_Media_MediaId");

                    b.Navigation("Media");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.Permission", b =>
                {
                    b.HasOne("MediaManager.Shared.Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Permissions_CreatedBy_Users_UserId");

                    b.HasOne("MediaManager.Shared.Domain.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("Permissions_UpdatedBy_Users_UserId");

                    b.Navigation("Creator");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.Role", b =>
                {
                    b.HasOne("MediaManager.Shared.Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Roles_CreatedBy_Users_UserId");

                    b.HasOne("MediaManager.Shared.Domain.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("Roles_UpdatedBy_Users_UserId");

                    b.Navigation("Creator");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.RolePermission", b =>
                {
                    b.HasOne("MediaManager.Shared.Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("RolePermissions_CreatedBy_Users_UserId");

                    b.HasOne("MediaManager.Shared.Domain.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("RolePermissions_PermissionId_Permissions_PermissionId");

                    b.HasOne("MediaManager.Shared.Domain.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("RolePermissions_RoleId_Role_RoleId");

                    b.Navigation("Creator");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.UserPermission", b =>
                {
                    b.HasOne("MediaManager.Shared.Domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("UserPermissions_CreatedBy_Users_UserId");

                    b.HasOne("MediaManager.Shared.Domain.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("UserPermissions_PermissionId_Permissions_PermissionId");

                    b.HasOne("MediaManager.Shared.Domain.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("UserPermissions_UserId_Users_UserId");

                    b.Navigation("Creator");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.LibraryBucket", b =>
                {
                    b.Navigation("LibraryItems");
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.LibraryItem", b =>
                {
                    b.Navigation("LibrarySubItems");
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.Media", b =>
                {
                    b.Navigation("History");

                    b.Navigation("LibraryItems");

                    b.Navigation("LibrarySubItems");
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("MediaManager.Shared.Domain.User", b =>
                {
                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
